### ISSUE TITLE
chalkboard.json not saving

### ISSUE THREAD

**Issue by SapinMalin** [rajgoel/reveal.js-plugins#95]
Hello, when I press 'd' during a presentation, nothing seems to happen. I do not see a JSON file being saved anywhere, and of course, when I reload the presentation, with 'src: "chalkboard.json"' set, my drawings are lost. Please help! 

I am using reveal.js 4.0.2 with the chalkboard version from this archive. The problem persists in Chrome and Firefox, on both Windows 10 and Ubuntu 18.04. Thank you!

**Comment by rajgoel** [comment]
Thanks for reporting this. The key used in the code didn't match the documentation. This should be fixed with 3d014332e1221bde99adf6cfd5aa5ea57b55263a.

**Comment by SapinMalin** [comment]
Hello. Downloading the JSON file now works with your update, thank you! However, when I open the file with the parameter 'src: "chalkboard.json"' and the JSON file in the same directory as my presentation, I still do not see the drawings from last time... Am I doing something wrong?

**Comment by rajgoel** [comment]
Don't know what you are doing, but did you check out the [demo](https://rajgoel.github.io/reveal.js-demos/chalkboard-demo.html#/) and its [source code](https://github.com/rajgoel/reveal.js-demos). Everything must(!) be hosted on `https` because modern browsers would raise a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) error otherwise.

**Comment by SapinMalin** [comment]
Thank you very much for the advice! It didn't work when running a local file, but when putting everything on a remote HTTPS server, it now works! Except for one thing: then I open the presentation on the remote server with the '?print-pdf' option, I still do not see the drawings, which is a major problem in my case... Any advice on how to get it working?

**Comment by rajgoel** [comment]
Sometimes, this happens to me as well. There is a problem with synching the toolchain with reveal.js and loading the json file. Most of the times it worked for me after reloading the page (I assume that the browser caches the files and has them ready when needed after reloading). Don't know whether I can find a reliable fix for this soon, but this is something I want to do asap.

**Comment by SapinMalin** [comment]
I see... Reloading does not fix it in my case, so I would really be interested in knowing when you find a fix for this, so I will open a new thread for this issue. Thank you!
